version: '2'

networks:
  app-tier:
    driver: bridge

services:
  phpfpm:
    image: minhtrung/phpfpm-app:0.1.0
    networks:
      - app-tier
  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - phpfpm
    networks:
      - app-tier
    ports:
      - '8091:8080'
      - '8444:443'
    volumes:
      - ./vhosts:/opt/bitnami/nginx/conf/server_blocks
  mariadb:
    image: bitnami/mariadb:latest
    environment:
        - MARIADB_USER=mini
        - MARIADB_PASSWORD=mini
        - MARIADB_DATABASE=mini
        - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
