kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-mariadb-mariadb-slave-0
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
